package com.blas.romanempirecounter.presentation.mainpage

enum class LatinPhrases(val phrase: String) {
    ALEA_IACTA_EST("Alea iacta est"),
    VENI_VIDI_VICI("Veni, vidi, vici"),
    CARPE_DIEM("Carpe diem"),
    COGITO_ERGO_SUM("Cogito, ergo sum"),
    IN_VINO_VERITAS("In vino veritas"),
    AMOR_VINCIT_OMNIA("Amor vincit omnia"),
    TEMPUS_FUGIT("Tempus fugit"),
    ET_TU_BRUTE("Et tu, Brute?"),
    MEMENTO_MORI("Memento mori"),
    AD_ASTRA_PER_ASPERA("Ad astra per aspera"),
    DULCE_ET_DECORUM_EST_PRO_PATRIA_MORI("Dulce et decorum est pro patria mori"),
    AUDENTES_FORTUNA_IUVAT("Audentes fortuna iuvat"),
    PAX_VOBISCUM("Pax vobiscum"),
    SI_VIS_PACEM_PARA_BELLUM("Si vis pacem, para bellum"),
    FORTIS_FORTUNA_ADIUVAT("Fortis fortuna adiuvat"),
    NUNC_EST_BIBENDUM("Nunc est bibendum"),
    DIVIDE_ET_IMPERA("Divide et impera"),
    VERITAS_VOS_LIBERABIT("Veritas vos liberabit"),
    HOMO_HOMINI_LUPUS("Homo homini lupus"),
    IGNORANTIA_LEGIS_NON_EXCUSAT("Ignorantia legis non excusat"),
    VENI_VIDI_AMAVI("Veni, vidi, amavi"),
    SIC_SEMPER_TYRANNIS("Sic semper tyrannis"),
    LABOR_OMNIA_VINCIT("Labor omnia vincit"),
    SEMPER_FIDELIS("Semper fidelis"),
    EX_NIHILO_NIHIL_FIT("Ex nihilo nihil fit"),
    FIAT_LUX("Fiat lux"),
    AD_INFINITUM("Ad infinitum"),
    STATUS_QUO("Status quo"),
    DE_GUSTIBUS_NON_EST_DISPUTANDUM("De gustibus non est disputandum"),
    ERRARE_HUMANUM_EST("Errare humanum est"),
    HIC_ET_NUNC("Hic et nunc"),
    IN_MEDIAS_RES("In medias res"),
    IN_SITU("In situ"),
    PER_ASPERA_AD_ASTRA("Per aspera ad astra"),
    QUID_PRO_QUO("Quid pro quo"),
    REQUIESCAT_IN_PACE("Requiescat in pace"),
    SCIENTIA_POTENTIA_EST("Scientia potentia est"),
    TABULA_RASA("Tabula rasa"),
    VOX_POPULI_VOX_DEI("Vox populi, vox Dei"),
    AUDE_SAPERE("Aude sapere"),
    CAVEAT_EMPTOR("Caveat emptor"),
    DE_FACTO("De facto"),
    EX_LIBRIS("Ex libris"),
    IN_ABSENTIA("In absentia"),
    MEA_CULPA("Mea culpa"),
    NON_PLUS_ULTRA("Non plus ultra"),
    PRO_BONO("Pro bono"),
    SINE_QUA_NON("Sine qua non"),
    AD_HOC("Ad hoc")
}