package com.blas.romanempirecounter.presentation.mainpage

enum class LatinPhrases(override val phrase: String): Quote {
    ALEA_IACTA_EST("Alea iacta est"),
    VENI_VIDI_VICI("Veni, vidi, vici"),
    CARPE_DIEM("Carpe diem"),
    ET_TU_BRUTE("Et tu, Brute?"),
    IN_VINO_VERITAS("In vino veritas"),
    SI_VIS_PACEM_PARA_BELLUM("Si vis pacem, para bellum"),
    AMOR_FATI("Amor fati"),
    QUO_VADIS("Quo vadis?"),
    MEMENTO_MORI("Memento mori"),
    AD_ASTRA_PER_ASPERA("Ad astra per aspera"),
    FABER_EST_QUISQUE_FORTUNAE("Faber est suae quisque fortunae"),
    AUDENTES_FORTUNA_IUVAT("Audentes fortuna iuvat"),
    PAX_ROMANA("Pax Romana"),
    TEMPUS_FUGIT("Tempus fugit"),
    FORTUNA_CAECA_EST("Fortuna caeca est"),
    DURA_LEX_SED_LEX("Dura lex, sed lex"),
    DIVIDE_ET_IMPERA("Divide et impera"),
    ACTA_NON_VERBA("Acta non verba"),
    HOMO_HOMINI_LUPUS("Homo homini lupus"),
    AD_HOC("Ad hoc"),
    AMOR_VINCIT_OMNIA("Amor vincit omnia"),
    DEUS_EX_MACHINA("Deus ex machina"),
    EX_NIHILO_NIHIL_FIT("Ex nihilo nihil fit"),
    SIC_TRANSIT_GLORIA_MUNDI("Sic transit gloria mundi"),
    COGITO_ERGO_SUM("Cogito, ergo sum"),
    NON_PLUS_ULTRA("Non plus ultra"),
    CAVEAT_EMPTOR("Caveat emptor"),
    ERRARUM_HUMANUM_EST("Errarum humanum est"),
    IN_MEDIAS_RES("In medias res"),
    VADE_MECUM("Vade mecum"),
    PANEM_ET_CIRCENSES("Panem et circenses"),
    VERITAS_VOS_LIBERABIT("Veritas vos liberabit"),
    LABOR_OMNIA_VINCIT("Labor omnia vincit"),
    EX_LIBRIS("Ex libris"),
    IN_ABSENTIA("In absentia"),
    DE_FACTO("De facto"),
    IN_FLAGRANTE_DELICTO("In flagrante delicto"),
    BONA_FIDE("Bona fide"),
    POST_SCRIPTUM("Post scriptum"),
    QUID_PRO_QUO("Quid pro quo"),
    SINE_QUA_NON("Sine qua non"),
    CETERIS_PARIBUS("Ceteris paribus"),
    AD_INFINITUM("Ad infinitum"),
    PERSONA_NON_GRATA("Persona non grata"),
    E_PLURIBUS_UNUM("E pluribus unum"),
    DEO_VOLENTE("Deo volente"),
    STATUS_QUO("Status quo"),
    IN_HOC_SIGNO_VINCES("In hoc signo vinces"),
    PRO_BONO("Pro bono"),
    TABULA_RASA("Tabula rasa"),
    PER_CAPITA("Per capita"),
    VOX_POPULI("Vox populi"),
    LAPSUS_LINGUAE("Lapsus linguae"),
    AD_NAUSEAM("Ad nauseam"),
    DE_IURE("De iure"),
    ET_CETERA("Et cetera"),
    AD_HOMINEM("Ad hominem"),
    DULCE_ET_DECORUM_EST("Dulce et decorum est pro patria mori"),
    FORTIS_FORTUNA_ADIUVAT("Fortis fortuna adiuvat"),
    NUNC_EST_BIBENDUM("Nunc est bibendum"),
    PECUNIA_NON_OLET("Pecunia non olet"),
    SUB_ROSA("Sub rosa"),
    ULTIMATUM("Ultimatum"),
    VIRTUS_UNITA_FORTIOR("Virtus unita fortior"),
    PER_ASPERA_AD_ASTRA("Per aspera ad astra"),
    DUM_SPIRO_SPERO("Dum spiro, spero"),
    FINIS_CORONAT_OPUS("Finis coronat opus"),
    O_TEMPORA_O_MORES("O tempora, o mores!"),
    ABSIT_INVIDIA("Absit invidia"),
    FELIX_CULPA("Felix culpa"),
    IN_SITU("In situ"),
    MAGNUM_OPUS("Magnum opus"),
    MALA_FIDE("Mala fide"),
    NIHIL_NOVI_SUB_SOLE("Nihil novi sub sole"),
    PRIMUS_INTER_PARES("Primus inter pares"),
    SIC_SEMPER_TYRANNIS("Sic semper tyrannis"),
    IUSTITIA_OMNIBUS("Iustitia omnibus"),
    MENS_SANA_IN_CORPORE_SANO("Mens sana in corpore sano"),
    NUNC_AUT_NUMQUAM("Nunc aut numquam"),
    PAX_VOBISCUM("Pax vobiscum"),
    PATER_PATRIAE("Pater patriae"),
    AD_MAIOREM_DEI_GLORIAM("Ad maiorem Dei gloriam"),
    CREDO_UT_INTELLIGAM("Credo ut intelligam"),
    FIAT_LUX("Fiat lux"),
    IN_PERPETUUM("In perpetuum"),
    VOX_CLAMANTIS_IN_DESERTO("Vox clamantis in deserto"),
    IN_ABSENTIA_LUCIS_TENEBRAE_VINCUNT("In absentia lucis, tenebrae vincunt"),
    LUX_IN_TENEBRIS("Lux in tenebris"),
    OMNIA_VINCIT_AMOR("Omnia vincit amor"),
    PRO_PATRIA("Pro patria"),
    A_PRIORI("A priori"),
    AD_AUGUSTA_PER_ANGUSTA("Ad augusta per angusta"),
    CITIUS_ALTIUS_FORTIUS("Citius, Altius, Fortius"),
    CORRUPTIO_OPTIMI_PESSIMA("Corruptio optimi pessima"),
    HODIE_MIHI_CRAS_TIBI("Hodie mihi, cras tibi"),
    SALUS_POPULI_SUPREMA_LEX_ESTO("Salus populi suprema lex esto"),
    AD_VITAM_AETERNAM("Ad vitam aeternam"),
    FORTITUDINE_VINCIMUS("Fortitudine vincimus"),
    IN_PACE("In pace"),
    NON_COMPOS_MENTIS("Non compos mentis"),
    AD_VICTORIAM("Ad victoriam"),
    ANTE_BELLUM("Ante bellum"),
    ARMA_VIRUMQUE_CANO("Arma virumque cano"),
    DIES_IRAE("Dies irae"),
    PRO_DEO_ET_PATRIA("Pro deo et patria"),
    SUB_IUDICE("Sub iudice"),
    IN_DUBIO_PRO_REO("In dubio pro reo"),
    VIVAT_IMPERATOR("Vivat imperator"),
    ABSENTE_REO("Absente reo"),
    AGNOSCO_VETERIS_VESTIGIA_FLAMMAE("Agnosco veteris vestigia flammae"),
    ANNUS_HORRIBILIS("Annus horribilis"),
    CORPUS_DELICTI("Corpus delicti"),
    DE_GUSTIBUS_NON_EST_DISPUTANDUM("De gustibus non est disputandum"),
    DUX_FEMINA_FACTI("Dux femina facti"),
    GLORIA_IN_EXCELSIS_DEO("Gloria in excelsis Deo"),
    IN_TOTO("In toto"),
    INTER_ARMA_ENIM_SILENT_LEGES("Inter arma enim silent leges"),
    NON_SERVIAM("Non serviam"),
    PECUNIA_REGIT_MUNDUM("Pecunia regit mundum"),
    QUAE_NOCENT_DOCENT("Quae nocent, docent"),
    SILENTIUM_EST_AURUM("Silentium est aurum"),
    VIRES_ACQUIRIT_EUNDO("Vires acquirit eundo"),
    UBI_BENE_IBI_PATRIA("Ubi bene, ibi patria"),
    FORTES_FORTUNA_ADIUVAT("Fortes fortuna adiuvat"),
    IGNIS_AURUM_PROBAT("Ignis aurum probat"),
    IURE_DIVINO("Iure divino"),
    OMNIA_POSSUNT("Omnia possunt"),
    POST_TENEBRAS_LUX("Post tenebras lux"),
    COGNOSCE_TE_IPSUM("Cognosce te ipsum"),
    QUOD_ERAT_DEMONSTRANDUM("Quod erat demonstrandum"),
    AMICUS_CERTUS_IN_RE_INCERTA("Amicus certus in re incerta cernitur"),
    NIHIL_OBSTAT("Nihil obstat"),
    AMOR_FATIS("Amor fatis"),
    LUX_MUNDI("Lux mundi"),
    CARTHAGO_DELENDA_EST("Carthago delenda est"),
    NIHIL_DURAT_IN_AETERNUM("Nihil durat in aeternum"),
    PER_DUAS_VIAS("Per duas vias"),
    ANNO_DOMINI("Anno Domini"),
    REQUIESCAT_IN_PACE("Requiescat in pace"),
    NON_SIBI_SED_OMNIBUS("Non sibi sed omnibus"),
    FIDES_ET_RATIO("Fides et ratio"),
    SEMPER_IDEM("Semper idem"),
    ORDO_AB_CHAO("Ordo ab chao"),
    OPUS_DEI("Opus Dei"),
    OMNIA_SUNT_COMMUNIA("Omnia sunt communia"),
    PRO_DEO("Pro Deo"),
    MORS_CERTA_HORA_INCERTA("Mors certa, hora incerta"),
    BELLUM_OMNIUM_CONTRA_OMNES("Bellum omnium contra omnes"),
    NULLA_DIES_SINE_LINEA("Nulla dies sine linea"),
    VERBA_VOLANT_SCRIPTA_MANENT("Verba volant, scripta manent"),
    SIC_ITUR_AD_ASTRA("Sic itur ad astra"),
    AD_LUCEM("Ad lucem"),
    SPES_MEUS_EST_IN_DEO("Spes meus est in Deo"),
    VERITAS_NUMQUAM_PERIT("Veritas numquam perit"),
    SIC_UT_EGO("Sic ut ego"),
    IN_UTROQUE_PARATUS("In utroque paratus"),
    TEMPORA_MUTANTUR("Tempora mutantur"),
    CORAM_DEO("Coram Deo"),
    IN_COELO_QUESCAMUS("In coelo quiescamus"),
    AUDIATUR_ET_ALTERA_PAR("Audiatur et altera pars"),
    BIS_DAT_QUI_CITO_DAT("Bis dat qui cito dat"),
    MENS_AGITAT_MOLESM("Mens agitat molem"),
    LUPUS_EST_HOMO_HOMINI("Lupus est homo homini"),
    TIMOR_DOMINI_INITIUM_SAPIENTIAE("Timor Domini initium sapientiae"),
    PRO_BONO_PUBLICO("Pro bono publico"),
    AMOR_TUUS_VERUS_EST("Amor tuus verus est"),
    NIHIL_DEI_NISI_SAPIENTIA("Nihil dei nisi sapientia"),
    IN_HAC_SIGNO_VINCES("In hac signo vinces"),
    PARVA_FERRO_VERBA("Parva ferro verba"),
    VINCIT_OMNIA_VERITAS("Vincit omnia veritas"),
    AD_MORTEM_FESTINAMUS("Ad mortem festinamus"),
    EX_UMBRA_IN_SOLEM("Ex umbra in solem"),
    IN_NOMINE_PATRIS("In nomine Patris"),
    JUSTITIA_OMNIUM_PRINCIPIUM("Justitia omnium principium"),
    MELIOR_DIES_VENIET("Melior dies veniet"),
    MULTUM_IN_PARVO("Multum in parvo"),
    NIHIL_DE_NIHILO("Nihil de nihilo"),
    NON_SOLUM_SED_ETIAM("Non solum, sed etiam"),
    NOSCE_HOSTEM_TUUM("Nosce hostem tuum"),
    PER_ANGUSTA_AD_AUGUSTA("Per angusta ad augusta"),
    SIC_PARVIS_MAGNA("Sic parvis magna"),
    SPES_ALIT_EXILES("Spes alit exiles"),
    IN_MEDIO_STAT_VIRTUS("In medio stat virtus"),
    IN_OMNIA_PARATUS("In omnia paratus"),
    NOSCE_TE_IPSUM("Nosce te ipsum"),
    VERITAS_LIBERABIT_VOS("Veritas liberabit vos"),
    SALUS_PATRIAE_SUPREMA_LEX("Salus patriae suprema lex"),
    ULTIMA_RATIONE("Ultima ratione"),
    AMICUS_VERUS_EST_RARA_AVIS("Amicus verus est rara avis"),
    GLORIA_EXCELSIS_DEO("Gloria in excelsis Deo"),
    HONOR_ET_FIDES("Honor et fides"),
    CAVE_CANEM("Cave canem"),
    PER_ASPERA_AD_VERITATEM("Per aspera ad veritatem"),
    VERITAS_ODIUM_PARIET("Veritas odium pariet"),
    LUX_MUNDUS_EST("Lux mundus est"),
    IN_MARGINE("In margine"),
    REUS_EX_MACHINA("Reus ex machina"),
    NIHIL_EX_NIHILO("Nihil ex nihilo"),
    PACE_TUOS("Pace tuos"),
    GRATIAS_AGO_TIBI("Gratias ago tibi"),
    EGO_SUM_LUX("Ego sum lux"),
    QUAE_SURSUM_VOLUNT_QUI("Quae sursum volunt qui"),
    ULTIMA_THULE("Ultima Thule"),
    SPES_ALIT("Spes alit"),
    PRIMA_LUX("Prima lux"),
    SOLVITUR_AMBULANDO("Solvitur ambulando"),
    VALE_DICTUM("Vale dictum"),
    SPES_EST_REPOSITA("Spes est reposita"),
    PARS_VITAE("Pars vitae"),
    SEMPER_MEMOR("Semper memor"),
    SIC_ITUR_AD_VERITATEM("Sic itur ad veritatem")
}






